name: Astra
description: Anticheat for a block game.
version: 0.0.1
main: com.horizonpvp.astra.AntiCheat
permissions:
  anticheat.bypass:
    description: Bypass for all anticheat checks
    default: op
  anticheat.broadcast:
    description: Receive anticheat notifications
    default: op
  anticheat.debug:
    description: Receive anticheat debug messages
    default: op